window.MATH_CASES = [
 // [group, name, tex, display]
 ['arrows','simple arrows','a \\to b,\\ a \\gets b,\\ a \\mapsto b,\\ A \\Rightarrow B,\\ A \\iff B',false],
 ['arrows','long arrows','\\longrightarrow\\ \\longleftarrow\\ \\Longrightarrow\\ \\Longleftrightarrow\\ \\longmapsto',false],
 ['arrows','extensible arrows','A \\xrightarrow{f} B \\xleftarrow[g]{\\text{long label}} C',true],
 ['arrows','hook/twohead/misc','\\hookrightarrow\\ \\twoheadrightarrow\\ \\leadsto\\ \\nearrow\\ \\rightleftharpoons\\ \\leftrightarrows',false],
 ['chemistry','reaction','\\ce{H2O -> H+ + OH-}',false],
 ['chemistry','equilibrium + condition','\\ce{N2 + 3H2 <=>[\\text{Fe}] 2NH3}',true],
 ['chemistry','ions and states','\\ce{CuSO4 . 5H2O},\\ \\ce{Ca^{2+}},\\ \\ce{A_{(aq)} + B_{(s)}}',false],
 ['accents','accents','\\hat{x}\\ \\bar{x}\\ \\vec{v}\\ \\dot{x}\\ \\ddot{x}\\ \\tilde{x}\\ \\mathring{A}',false],
 ['accents','wide accents','\\widehat{xyz}\\ \\widetilde{abc}\\ \\overline{x+y}\\ \\underline{a+b}\\ \\overrightarrow{AB}\\ \\overleftarrow{CD}',false],
 ['accents','braces','\\overbrace{a+\\cdots+a}^{n}\\ \\underbrace{b+\\cdots+b}_{m}',true],
 ['stack','over/under set','\\overset{\\text{def}}{=}\\ \\underset{x}{\\operatorname{argmax}}\\ \\stackrel{?}{=}\\ \\operatorname*{arg\\,min}_{\\theta} L',true],
 ['stack','limits','\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1,\\ \\sum_{\\substack{i=1\\\\ i \\neq j}}^{n} a_i,\\ \\prod_{k=1}^{\\infty}',true],
 ['fractions','inline fractions','\\frac{TP}{TP+FP} = \\tfrac{1}{2},\\ \\frac{a+b}{c}',false],
 ['fractions','nested fraction (inline: script sizes, as TeX)','\\frac{\\frac{a}{b}}{\\frac{c}{d}} \\ne \\dfrac{\\dfrac{a}{b}}{\\dfrac{c}{d}}',false],
 ['fractions','fractions','\\frac{a}{b}\\ \\dfrac{a}{b}\\ \\tfrac{a}{b}\\ \\binom{n}{k}\\ \\cfrac{1}{1+\\cfrac{1}{1+x}}',true],
 ['roots','roots','\\sqrt{x}\\ \\sqrt[3]{x+1}\\ \\sqrt{\\frac{a}{b}}',false],
 ['delimiters','delimiters','\\left( \\frac{a}{b} \\right)\\ \\left[ x \\right]\\ \\left\\{ y \\right\\}\\ \\left\\langle v \\right\\rangle\\ \\lfloor x \\rfloor\\ \\lceil x \\rceil\\ \\|x\\|',true],
 ['delimiters','sized + one-sided','\\big( \\Big( \\bigg( \\Bigg(\\ \\left. \\frac{df}{dx} \\right|_{x=0}',true],
 ['matrices','bmatrix/vmatrix','\\begin{bmatrix} 1 & 0 \\\\ 0 & 1 \\end{bmatrix}\\ \\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}\\ \\begin{Vmatrix} x \\end{Vmatrix}',true],
 ['matrices','array with rules','\\left[\\begin{array}{cc|c} 1 & 2 & 3 \\\\ \\hline 4 & 5 & 6 \\end{array}\\right]',true],
 ['matrices','dots','\\begin{pmatrix} a_{11} & \\cdots & a_{1n} \\\\ \\vdots & \\ddots & \\vdots \\\\ a_{m1} & \\cdots & a_{mn} \\end{pmatrix}',true],
 ['matrices','smallmatrix','\\left(\\begin{smallmatrix} a & b \\\\ c & d \\end{smallmatrix}\\right)',false],
 ['environments','align','\\begin{align} f(x) &= (x+1)^2 \\\\ &= x^2 + 2x + 1 \\end{align}',true],
 ['environments','gather + tag','\\begin{gather} a = b \\tag{1} \\\\ c = d \\end{gather}',true],
 ['environments','cases','f(x) = \\begin{cases} x^2 & x \\ge 0 \\\\ -x & x < 0 \\end{cases}',true],
 ['enclose','cancel family','\\cancel{a}\\ \\bcancel{b}\\ \\xcancel{c}\\ \\cancelto{0}{x}',false],
 ['enclose','boxed','\\boxed{E = mc^2}\\ \\fbox{text}',false],
 ['fonts','alphabets','\\mathbb{R}\\ \\mathcal{L}\\ \\mathfrak{g}\\ \\mathscr{F}\\ \\mathsf{A}\\ \\mathtt{x}\\ \\mathbf{v}\\ \\boldsymbol{\\alpha}\\ \\mathrm{d}x',false],
 ['fonts','greek','\\alpha\\beta\\gamma\\delta\\epsilon\\varepsilon\\theta\\vartheta\\lambda\\mu\\pi\\sigma\\phi\\varphi\\omega\\ \\Gamma\\Delta\\Theta\\Lambda\\Sigma\\Phi\\Psi\\Omega',false],
 ['operators','integrals','\\int_a^b\\ \\iint\\ \\iiint\\ \\oint_C\\ \\int\\limits_0^1',true],
 ['operators','symbols','\\partial\\ \\nabla\\ \\infty\\ \\forall\\ \\exists\\ \\in\\ \\notin\\ \\subset\\ \\supseteq\\ \\cup\\ \\cap\\ \\emptyset\\ \\neq\\ \\leq\\ \\geq\\ \\approx\\ \\equiv\\ \\sim\\ \\propto\\ \\pm\\ \\times\\ \\cdot\\ \\circ',false],
 ['operators','mod + functions','a \\equiv b \\pmod{n},\\ a \\bmod n,\\ \\sin\\theta\\ \\log_2 n\\ \\exp(x)\\ \\max_i\\ \\det A',false],
 ['misc','color','\\color{red}{x} + \\textcolor{blue}{y}',false],
 ['misc','primes + spacing','f\'(x),\\ f\'\'(x),\\ a\\,b\\;c\\quad d\\qquad e\\!f',false],
 ['misc','phantom + not','\\phantom{x}y,\\ \\not\\subset,\\ \\not=',false],
 ['misc','text Persian','\\text{اگر } x > 0 \\text{ آنگاه } y = 1',true],
 ['misc','units (siunitx-like)','9.81\\,\\mathrm{m/s^2},\\ 25\\,^{\\circ}\\mathrm{C}',false]
];
