/**
 * Build docs/about-kelk-and-samples.js from docs/about-kelk-and-samples.<lang>.md
 * — the page loads the script (a <script> tag works from file://, fetch does not).
 * Run with Node after editing a sample:  node tools/build-samples.js
 * A new language is a new file (about-kelk-and-samples.ar.md → KelkSamples.ar).
 */
const fs = require('fs'), path = require('path');
const dir = path.join(__dirname, '..', 'docs');
const samples = {};
fs.readdirSync(dir).forEach(function (f) {
    const m = /^about-kelk-and-samples\.([a-z]{2,3})\.md$/.exec(f);
    if (m) samples[m[1]] = { name: f, markdown: fs.readFileSync(path.join(dir, f), 'utf8') };
});
const js = '/**\n * Kelk: about + guide + samples, one document per interface language — generated by\n' +
    ' * tools/build-samples.js from docs/about-kelk-and-samples.<lang>.md; do not edit by hand.\n */\n' +
    'window.KelkSamples = ' + JSON.stringify(samples, null, 1) + ';\n';
fs.writeFileSync(path.join(dir, 'about-kelk-and-samples.js'), js);
console.log('docs/about-kelk-and-samples.js:', Object.keys(samples).join(', '), Buffer.byteLength(js), 'bytes');
