/**
 * Build assets/icons.js — only the Lucide icons Kelk uses, instead of the
 * whole library (vendor/lucide.min_1.48.0.js, ~410 KB). Run with Node after
 * adding an icon:  node tools/build-icons.js
 * Icons used: every data-lucide="…" in index.html and scripts/*.js, plus EXTRA
 * (names built at run time, e.g. setIcon(btn, dark ? 'sun' : 'moon')).
 */
const fs = require('fs'), path = require('path'), vm = require('vm');
const root = path.join(__dirname, '..');
const EXTRA = ['sun', 'moon', 'columns-2', 'rows-2', 'copy', 'check'];

const sandbox = { window: {}, self: {}, globalThis: {} };
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root, 'vendor/lucide.min_1.48.0.js'), 'utf8'), sandbox);
const lucide = sandbox.lucide || sandbox.window.lucide || sandbox.self.lucide;
const icons = lucide.icons;

const files = [path.join(root, 'index.html')].concat(fs.readdirSync(path.join(root, 'scripts')).map(f => path.join(root, 'scripts', f)));
const used = new Set(EXTRA);
files.forEach(f => (fs.readFileSync(f, 'utf8').match(/data-lucide="([a-z0-9-]+)"/g) || []).forEach(m => used.add(m.slice(13, -1))));

const pascal = n => n.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join('');
const out = {};
[...used].sort().forEach(name => {
    const node = icons[pascal(name)];
    if (!node) throw new Error('unknown icon: ' + name);
    // [tag, attrs] children → SVG markup
    out[name] = node.map(([tag, attrs]) => '<' + tag + Object.keys(attrs).filter(k => k !== 'key')
        .map(k => ' ' + k + '="' + String(attrs[k]).replace(/"/g, '&quot;') + '"').join('') + '/>').join('');
});

const js = `/**
 * Kelk icons — a subset of Lucide 1.48.0 (ISC License, https://lucide.dev),
 * generated by tools/build-icons.js; do not edit by hand.
 * Same use as Lucide: <i data-lucide="name"></i>, then lucide.createIcons({ root }).
 */
(function (global) {
    'use strict';
    var ICONS = ${JSON.stringify(out, null, 4).replace(/\n/g, '\n    ')};
    function svg(name, i) {
        var s = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
        s.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
        s.setAttribute('width', '24'); s.setAttribute('height', '24'); s.setAttribute('viewBox', '0 0 24 24');
        s.setAttribute('fill', 'none'); s.setAttribute('stroke', 'currentColor'); s.setAttribute('stroke-width', '2');
        s.setAttribute('stroke-linecap', 'round'); s.setAttribute('stroke-linejoin', 'round');
        s.setAttribute('aria-hidden', 'true');
        s.setAttribute('class', ('lucide lucide-' + name + ' ' + (i.getAttribute('class') || '')).trim());
        s.setAttribute('data-lucide', name);
        s.innerHTML = ICONS[name];
        return s;
    }
    function createIcons(opts) {
        var root = (opts && opts.root) || document;
        Array.prototype.forEach.call(root.querySelectorAll('i[data-lucide]'), function (i) {
            var name = i.getAttribute('data-lucide');
            if (ICONS[name]) i.parentNode.replaceChild(svg(name, i), i);
            else if (global.console) console.warn('icon not in assets/icons.js: ' + name + ' (run tools/build-icons.js)');
        });
    }
    global.lucide = { createIcons: createIcons, icons: ICONS };
})(typeof window !== 'undefined' ? window : this);
`;
fs.writeFileSync(path.join(root, 'assets/icons.js'), js);
console.log('assets/icons.js:', used.size, 'icons,', Buffer.byteLength(js), 'bytes');
